services:
  db:
    image: db-image
    deploy:
      replicas: 2
    ports:
      - "3306:3306"
    networks:
      - vikram
  auth_service:
    image: auth-image
    deploy:
      replicas: 2
    ports:
      - "5001:5001"
    networks:
      - vikram
  book_service:
    image: book-image
    deploy:
      replicas: 2
    ports:
      - "5002:5002"
    networks:
      - vikram
  borrow_service:
    image: borrow-image
    deploy:
      replicas: 2
    ports:
      - "5003:5003"
    networks:
      - vikram
  
  frontend:
    image: frontend-image
    deploy:
      replicas: 2
    ports:
      - "5000:5000"
    networks:
      - vikram


  networks:
    vikram:
      driver: overlay
